FROM node:16-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci

# Copy configuration files
COPY postcss.config.cjs ./
COPY tailwind.config.cjs ./
COPY vite.config.cjs ./

# Copy the rest of the frontend code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host"]