apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: todolist
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todolist
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password@mongodb:27017/todo-app?authSource=admin"